

export const types = {
   GET_ALL_MOVIES : "GET_ALL_MOVIES",
   GET_MOVIE_DETAIL: "GET_MOVIE_DETAIL",
   FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
   FILTER_BY_ALPHABET: "FILTER_BY_ALPHABET",
   FILTER_BY_RATING: "FILTER_BY_RATING",
   RESET_FILTER: "RESET_FILTER",
   FILTER_BY_NAME: "FILTER_BY_NAME"
}